development: &development
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: thinkrelevance_development
  pool: 5
  min_messages: warning

test:
  <<: *development
  database: thinkrelevance_test
